//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobBoardv3.DATA.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Application
    {
        [DisplayName("Application Id")]
        public int ApplicationId { get; set; }
        [DisplayName("Available Position Id")]
        public int OpenPositionId { get; set; }
        [DisplayName("User Id")]
        public string UserId { get; set; }
        [DisplayName("Application Date")]
        public System.DateTime ApplicationDate { get; set; }
        [DisplayName("Manager Notes")]
        public string ManagerNotes { get; set; }
        [DisplayName("Status")]
        public int ApplicationStatus { get; set; }
    
        public virtual ApplicationStatu ApplicationStatu { get; set; }
        public virtual OpenPosition OpenPosition { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }

}
