//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobBoardv3.DATA.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Position
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Position()
        {
            this.OpenPositions = new HashSet<OpenPosition>();
        }

        [DisplayName("Position Id")]
        public int PositionId { get; set; }
        public string Title { get; set; }
        [DisplayName("Job Description")]
        public string JobDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpenPosition> OpenPositions { get; set; }
    }
}
